DBAAS-338 Disable wait_for_columnstore_active output unless CS_DEBUG=1 specified as env variable. Add configurable amount of retries in wait_for_columnstore_active Add logic to update server-id in my.cnf to last digit of ip every restart in dbinit to make replication work

diff --git a/columnstore/dbinit b/columnstore/dbinit
--- a/columnstore/dbinit
+++ b/columnstore/dbinit
@@ -22,6 +22,10 @@ wait_for_procmon()
     done
 }
 
+# hack to ensure server-id is set to unique value per vm because my.cnf is
+# not in a good location for a volume
+SERVER_ID=$(hostname -i | cut -d "." -f 4)
+sed -i "s/server-id =.*/server-id = $SERVER_ID/" /usr/local/mariadb/columnstore/mysql/my.cnf 
 
 # Initialize CS only once.
 if [ -e $FLAG ]; then
@@ -47,6 +51,11 @@ else
         # columnstore to startup by some other means
         echo "Waiting for columnstore to start to run post install files"
         /usr/sbin/wait_for_columnstore_active
+        if [ 1 -eq $? ]; then
+            # exit now if columnstore did not start
+            echo "ERROR: ColumnStore did not start so custom install files not run."
+            exit 1
+        fi
     fi
 
     # Create custom database for scripts if needed based on CS_DATABASE env var
@@ -77,9 +86,8 @@ else
                 /bin/sh -x $f 2>&1
             fi;
         done;
-        echo "Finish at $(date)"
+        echo "Container initialization complete at $(date)"
     fi
-    echo "Container initialization complete at $(date)"
     touch $FLAG
 fi
 exit 0;
